### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by cubedhuang** [organization-x/ai-on-thumbs#140]
are u repeating `<LinearGradient colors={['#8976C2', '#E6E8FB']}` on every single course page AAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHH my programmer heart can't take it anymore

idea: make a Component with the styles and colors for the sheet so that you can have like `<Layout>` instead of the repeated thing

also for components like `LessonButton` rather than having a color prop you should probably just make variants like `"option"` and stuff (e.g. `<LessonButton variant="option">` rather than `<LessonButton buttonColor="#8976C2">`) and then have all of the colors located in the component file so that if you need to make any modifications for accessibility or theming you don't have to FIND AND REPLACE EVERY SINGLE INSTANCE OF THE COLOR STRING EVERYWHERE sorry i got a little heated there

anyways i probably shouldn't be making an issue on this repo but i said what had to be said

**Comment by neverabsolute** [comment]
you're bad 👎
